move to blink
ticktok-io/ticktok-java-client pull request #10
Opened 2019-03-20 15:31 UTC by amaziagur

2019-03-20 20:07 UTC, rockem approved these changes

2019-03-20 20:07 UTC, rockem requested changes

2019-03-20 20:07 UTC, rockem commented on pom.xml
> +    <version>0.4.1</version>
4.1 ?

2019-03-21 07:29 UTC, amaziagur commented on pom.xml
> +    <version>0.4.1</version>
heheh, opps

2019-03-21 07:30 UTC, amaziagur commented on pom.xml
> +    <version>0.4.1</version>
fixed

2019-03-21 07:46 UTC, rockem requested changes

2019-03-21 07:46 UTC, rockem commented on pom.xml
> +    <version>0.3.0</version>
Amazia, this is a patch with no added functionality, it should be 0.2.1

2019-03-21 07:55 UTC, rockem approved these changes

2019-03-21 12:54 UTC, merged