Allow to tick a specific clock
ticktok-io/ticktok-java-client pull request #14
Opened 2019-05-08 12:05 UTC by amaziagur

2019-05-08 12:16 UTC, rockem requested changes

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/Ticktok.java
> +        new RestClockCreator(options).tick(new ClockRequest(name, schedule));
RestClockCreator ==> only creates
ClockRequest ==> requesting a clock 

you should use other classes or rename these

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/Ticktok.java
> +        new RestClockCreator(options).tick(new ClockRequest(name, schedule));
I think you can have separate class for each action it will be more clean

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/server/rest/RestClockCreator.java
> +            throw new ConnectionException("Connection error", e);
I think you should catch IOException on the top level only

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/server/rest/RestClockCreator.java
> +        switch (expectedMethod){
no no

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/server/rest/UrlResolver.java
> +        StringBuilder url = resolved.append("?").append("access_token=").append(this.options.getToken());
there's uribuilder you can use

2019-05-08 12:16 UTC, rockem commented on src/main/java/io/ticktok/client/server/rest/UrlResolver.java
> +        StringBuilder url = resolved.append("?").append("access_token=").append(this.options.getToken());
also too much state, why?

2019-05-08 12:16 UTC, rockem commented on src/test/java/test/io/ticktok/client/server/ClockCreatorTest.java
> +public class    ClockCreatorTest {
space
what is this class?

2019-05-08 12:16 UTC, rockem commented on src/test/java/test/io/ticktok/client/server/support/TicktokServer.java
> +    public String tickFor() {
tick for what?

2019-05-08 12:39 UTC, rockem requested changes

2019-05-08 12:39 UTC, rockem commented on src/main/java/io/ticktok/client/Ticktok.java
> +        new RestClockCreator(options).tick(new ClockRequest(name, schedule));
Also, where's the test for it?

2019-05-13 14:24 UTC, amaziagur commented on src/main/java/io/ticktok/client/Ticktok.java
> +        new RestClockCreator(options).tick(new ClockRequest(name, schedule));
for now didn't complete it. let think together on the best option to test here

2019-05-13 14:24 UTC, amaziagur commented on src/main/java/io/ticktok/client/server/rest/RestClockCreator.java
> +            throw new ConnectionException("Connection error", e);
fixed

2019-05-13 14:24 UTC, amaziagur commented on src/main/java/io/ticktok/client/server/rest/RestClockCreator.java
> +        switch (expectedMethod){
fixed

2019-05-13 14:24 UTC, amaziagur commented on src/main/java/io/ticktok/client/server/rest/UrlResolver.java
> +        StringBuilder url = resolved.append("?").append("access_token=").append(this.options.getToken());
fixed

2019-05-13 14:25 UTC, amaziagur commented on src/test/java/test/io/ticktok/client/server/ClockCreatorTest.java
> +public class    ClockCreatorTest {
fixed

2019-05-13 14:25 UTC, amaziagur commented on src/test/java/test/io/ticktok/client/server/support/TicktokServer.java
> +    public String tickFor() {
fixed

2019-05-16 07:53 UTC, rockem approved these changes

2019-05-16 07:54 UTC, merged